# Generated by Django 5.1.4 on 2024-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininformations',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
