# Generated by Django 5.1.4 on 2024-12-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_maininformations_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maininformations',
            old_name='img',
            new_name='img_back',
        ),
        migrations.AddField(
            model_name='maininformations',
            name='owner_img',
            field=models.ImageField(null=True, upload_to='Owner_media', verbose_name='Owner Image'),
        ),
    ]
