# Generated by Django 5.1.4 on 2024-12-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_maininformations_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, verbose_name='Skill name')),
                ('skill_percent', models.IntegerField(verbose_name='Skill percent')),
            ],
        ),
    ]
