# Generated by Django 5.1.4 on 2024-12-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_forskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('company', models.CharField(max_length=255, verbose_name='Company name')),
                ('txt', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.AlterModelOptions(
            name='forskills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skill'},
        ),
    ]
