# Generated by Django 5.1.4 on 2024-12-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_about_alter_forskills_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='dt_start',
            field=models.DateField(null=True, verbose_name='Date end'),
        ),
    ]
