# Generated by Django 5.1.4 on 2024-12-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_about_dt_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='dt_end',
            field=models.DateField(null=True, verbose_name='Date end'),
        ),
        migrations.AlterField(
            model_name='about',
            name='dt_start',
            field=models.DateField(null=True, verbose_name='Date start'),
        ),
    ]
