# Generated by Django 5.1.4 on 2024-12-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_about_present_alter_about_dt_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(verbose_name='About Text')),
            ],
        ),
    ]
