# Generated by Django 5.1.4 on 2024-12-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_staffstory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouttxt',
            options={'verbose_name': 'About text', 'verbose_name_plural': 'About text'},
        ),
        migrations.AlterField(
            model_name='staffstory',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='Icone'),
        ),
    ]
