# Generated by Django 5.1.4 on 2024-12-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.TextField(verbose_name='Subtitle')),
                ('img', models.ImageField(upload_to='comp_works', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Completed work',
                'verbose_name_plural': 'Completed works',
            },
        ),
    ]
