# Generated by Django 5.1.4 on 2024-12-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_subwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subwork',
            name='many_about',
        ),
        migrations.CreateModel(
            name='SubAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('subworkk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subaboutt', to='main.subwork')),
            ],
        ),
    ]
