# Generated by Django 5.1.4 on 2024-12-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_sendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data'),
        ),
    ]
