# Generated by Django 5.1.4 on 2024-12-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_sendmessage_options_maininformations_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maininformations',
            old_name='address',
            new_name='address_1',
        ),
        migrations.AddField(
            model_name='maininformations',
            name='address_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
    ]
