# Generated by Django 5.1.4 on 2024-12-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_address_maininformations_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininformations',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
