# Generated by Django 5.1.4 on 2024-12-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_maininformations_address_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(verbose_name='instagram')),
                ('linkedin', models.URLField(verbose_name='linkedin')),
                ('facebook', models.URLField(verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
