# Generated by Django 5.1.4 on 2024-12-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_siteurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininformations',
            name='icon',
            field=models.ImageField(null=True, upload_to='Icon', verbose_name='Icon'),
        ),
    ]
