# Generated by Django 5.1.4 on 2024-12-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_maininformations_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Informations',
            },
        ),
    ]
